[package]
name = "pi-finder"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freedesktop_entry_parser = "1"
gtk = { git = "https://github.com/gtk-rs/gtk3-rs.git" }
once_cell = "1.8"
